// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package twitter_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TwitterScraperClient is the client API for TwitterScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwitterScraperClient interface {
	GetTwitterData(ctx context.Context, in *GetTwitterDataRequest, opts ...grpc.CallOption) (*GetTwitterDataResponse, error)
}

type twitterScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewTwitterScraperClient(cc grpc.ClientConnInterface) TwitterScraperClient {
	return &twitterScraperClient{cc}
}

func (c *twitterScraperClient) GetTwitterData(ctx context.Context, in *GetTwitterDataRequest, opts ...grpc.CallOption) (*GetTwitterDataResponse, error) {
	out := new(GetTwitterDataResponse)
	err := c.cc.Invoke(ctx, "/pb.TwitterScraper/GetTwitterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwitterScraperServer is the server API for TwitterScraper service.
// All implementations must embed UnimplementedTwitterScraperServer
// for forward compatibility
type TwitterScraperServer interface {
	GetTwitterData(context.Context, *GetTwitterDataRequest) (*GetTwitterDataResponse, error)
	mustEmbedUnimplementedTwitterScraperServer()
}

// UnimplementedTwitterScraperServer must be embedded to have forward compatible implementations.
type UnimplementedTwitterScraperServer struct {
}

func (UnimplementedTwitterScraperServer) GetTwitterData(context.Context, *GetTwitterDataRequest) (*GetTwitterDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTwitterData not implemented")
}
func (UnimplementedTwitterScraperServer) mustEmbedUnimplementedTwitterScraperServer() {}

// UnsafeTwitterScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwitterScraperServer will
// result in compilation errors.
type UnsafeTwitterScraperServer interface {
	mustEmbedUnimplementedTwitterScraperServer()
}

func RegisterTwitterScraperServer(s grpc.ServiceRegistrar, srv TwitterScraperServer) {
	s.RegisterService(&TwitterScraper_ServiceDesc, srv)
}

func _TwitterScraper_GetTwitterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTwitterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterScraperServer).GetTwitterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TwitterScraper/GetTwitterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterScraperServer).GetTwitterData(ctx, req.(*GetTwitterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TwitterScraper_ServiceDesc is the grpc.ServiceDesc for TwitterScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwitterScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TwitterScraper",
	HandlerType: (*TwitterScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTwitterData",
			Handler:    _TwitterScraper_GetTwitterData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twitter_service.proto",
}
